[project]
name = "intern_gmail_agent"
version = "0.1.0"
description = "intern-gmail-agent using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.119.0,<1.0.0"
]

[project.scripts]
intern_gmail_agent = "intern_gmail_agent.main:run"
run_crew = "intern_gmail_agent.main:run"
train = "intern_gmail_agent.main:train"
replay = "intern_gmail_agent.main:replay"
test = "intern_gmail_agent.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
